#! /bin/bash

set -e


if [ $EUID -ne 0 ]; then
	echo "$(basename $0) must be run as root"
	exit 1
fi

if ! frzr-release > /dev/null; then
	echo "Not currently running a frzr deployment"
	exit 1
fi

MOUNT_PATH=/frzr_root

if ! mountpoint -q ${MOUNT_PATH}; then
        mkdir -p ${MOUNT_PATH}
        mount -L frzr_root ${MOUNT_PATH}
        sleep 5
fi

if ! mountpoint -q ${MOUNT_PATH}/boot && ls -1 /dev/disk/by-label | grep frzr_efi > /dev/null; then
        mkdir -p ${MOUNT_PATH}/boot
        mount -L frzr_efi ${MOUNT_PATH}/boot
        sleep 5
fi

DEPLOYMENT=$(frzr-release)

# set rootfs btrfs subvolume to read-write mode
btrfs property set -fts / ro false
systemctl daemon-reload

# copy package database and refresh
if [ -d /usr/var/lib/pacman/local ] && [ ! -d /var/lib/pacman/local ]; then
	mkdir -p /var/lib/pacman
	cp -r /usr/var/lib/pacman/local /var/lib/pacman/
	pacman -Sy
fi

echo "frzr deployment ${DEPLOYMENT} unlocked"
