name: Tests

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Fix files permission
      run: |
        chmod +x frzr* __frzr*
    - name: Run tests
      run: |
        cd test
        ./run.sh
    - name: Test Install
      run: |
        docker run -u root --rm --entrypoint=/workdir/test/test-install.sh -v $(pwd):/workdir -v /dev:/dev --privileged archlinux:latest
    - name: Test Removal
      run: |
        docker run -u root --rm --entrypoint=/workdir/test/test-removal.sh -v $(pwd):/workdir -v /dev:/dev --privileged archlinux:latest

